#! /bin/sh

#autostart apps

pgrep -x sxhkd > /dev/null || sxhkd &
xrdb merge ~/.Xresources &

picom &

slack -u &

# workspaces

if [[ $(xrandr -q | grep 'VGA-1 connected') ]]; then
  bspc monitor DVI-D-1 -d 1 2 3 4 5 6
  bspc monitor VGA-1 -d 7 8 9 0
else
  bspc monitor DVI-D-1 -d 1 2 3 4 5 6 7 8 9 0
fi

~/.config/polybar/launch.sh &

bspc config focus_follows_pointer true

bspc config top_padding 15

# borders
bspc config focused_border_color "#ECBDBB"
bspc config normal_border_color "#282c34"
bspc config border_width 1
bspc config borderless_monocle true

#gaps
bspc config gapless_monocle false
bspc config window_gap 10
bspc config split_ratio 0.60

#moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#rules
bspc rule -a pavucontrol
bspc rule -a google-chrome-stable desktop='^1' follow=on
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a code desktop='^2' follow=on
bspc rule -a kitty desktop='^3'
bspc rule -a thunar desktop='^5'
bspc rule -a spotify desktop='^7' follow=on
bspc rule -a discord desktop='^0'
bspc rule -a slack desktop="^9" follow=on
